name: p115updatedb builder

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          arch: ["amd64", "arm64"]
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set Up QEMU
          uses: docker/setup-qemu-action@v3

        - name: Set Up Buildx
          uses: docker/setup-buildx-action@v3

        - name: Package through pyinstaller
          run: |
            mkdir rootfs
            docker buildx build --platform linux/${{ matrix.arch }} --file ./package/p115strmhelper/Dockerfile --output type=local,dest=./rootfs .
            cp ./rootfs/p115updatedb ./p115updatedb-${{ matrix.arch }}
          shell: pwsh

        - name: Upload linux file
          uses: actions/upload-artifact@v4
          with:
            name: p115updatedb-${{ matrix.arch }}
            path: p115updatedb-${{ matrix.arch }}

  release:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4

      - 
        name: Download Artifact
        uses: actions/download-artifact@v4

      - 
        name: Rename
        shell: bash
        run: |
            mkdir ./release
            mv ./p115updatedb-amd64/p115updatedb-amd64 ./release
            mv ./p115updatedb-arm64/p115updatedb-arm64 ./release

      - 
        name: Delete Release
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: p115updatedb
          delete_release: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Release
        uses: softprops/action-gh-release@v2
        with:
            name: p115updatedb
            tag_name: p115updatedb
            files: |
                ./release/p115updatedb-amd64
                ./release/p115updatedb-arm64
